name: cmc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Adjust this to match your Flutter's Dart SDK version
  # e.g., for Flutter 3.22.x (Dart 3.4.x) use: sdk: '>=3.4.0 <4.0.0'
  # e.g., for Flutter 3.19.x (Dart 3.3.x) use: sdk: '>=3.3.0 <4.0.0'
  # To check: run `flutter --version`
  sdk: '>=3.4.0 <4.0.0' # EXAMPLE: Please verify and adjust

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # Using a common stable version, verify with `flutter pub outdated`
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0
  image_picker: ^1.1.2 # ADDED image_picker (check pub.dev for the absolute latest stable version)
  flutter_markdown: ^0.7.7+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Using a common stable version, verify with `flutter pub outdated`
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# flutter_launcher_icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  # Optional adaptive icon settings (see previous advice)
  # adaptive_icon_background: "#2E7D32"
  # adaptive_icon_foreground: "assets/images/app_logo_foreground.png"